name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Özellikler / Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Hata Düzeltmeleri / Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Bakım / Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'perf'
      - 'test'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: 'Bu sürümde değişiklik yok. / No changes in this release.'
template: |
  # 📦 Sürüm: v$RESOLVED_VERSION
  > Yayın tarihi: $DATE  
  > Önceki sürüm: $PREVIOUS_TAG

  ## 📝 Değişiklikler / Changes

  $CHANGES

  ---

  ## 👥 Katkıda Bulunanlar / Contributors

  $CONTRIBUTORS 