name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Özellikler / Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Hata Düzeltmeleri / Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Bakım / Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'perf'
      - 'test'
      - 'chore(ci)'
      - 'chore(deps)'
      - 'chore(release)'
      - 'chore(*)'
  - title: '📚 Dokümantasyon / Documentation'
    labels:
      - 'docs'
      - 'documentation'
      - 'readme'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: 'Bu sürümde değişiklik yok. / No changes in this release.'
template: |
  > Önceki sürüm: $PREVIOUS_TAG

  ## 📝 Değişiklikler / Changes

  $CHANGES

  ---
  ## 🧪 Otomatik Kalite Kontrolleri / QA Outputs

