name: Publish Release

on:
  push:
    tags:
      - '*'

# Add permissions for gh release upload
permissions:
  contents: write

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib

      - name: Run filter lint
        run: |
          python scripts/filter_lint.py > lint_output.txt
      - name: Run domain check
        run: |
          python scripts/domain_check.py > domain_check_output.txt
      - name: Run filter stats
        run: |
          python scripts/filter_stats.py > stats_output.txt

      - name: Generate plot images
        run: |
          python scripts/plot_filter_stats.py

      - name: Combine QA outputs
        run: |
          echo '### Filter Lint\n' > release_qa.txt
          cat lint_output.txt >> release_qa.txt
          echo '\n### Domain Check\n' >> release_qa.txt
          cat domain_check_output.txt >> release_qa.txt
          echo '\n### Filter Stats\n' >> release_qa.txt
          cat stats_output.txt >> release_qa.txt

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} tld_distribution.png active_inactive_distribution.png

      - name: Append images to QA outputs
        env:
          GH_REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "\n### Generated Plots\n" >> release_qa.txt
          echo "<img src='https://github.com/${GH_REPO}/releases/download/${TAG_NAME}/tld_distribution.png' alt='TLD Distribution' width='600'/>" >> release_qa.txt
          echo "<img src='https://github.com/${GH_REPO}/releases/download/${TAG_NAME}/active_inactive_distribution.png' alt='Active/Inactive Distribution' width='600'/>" >> release_qa.txt

      - uses: release-drafter/release-drafter@v6.1.0
        with:
          publish: true
          append-body-from-file: release_qa.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
