name: Version Bump & Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  version-bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Remove duplicate domains
        run: |
          python scripts/remove_duplicates.py

      - name: Lint filter (check format, duplicates, invalid chars)
        run: |
          python scripts/filter_lint.py

      - name: Domain check (optional, devam etsin)
        run: |
          python scripts/domain_check.py || true

      - name: Filter stats (bilgilendirme amaçlı)
        run: |
          python scripts/filter_stats.py

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Determine bump type from PR title
        id: bump_type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if echo "$PR_TITLE" | grep -iq '\[bump:major\]'; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif echo "$PR_TITLE" | grep -iq '\[bump:minor\]'; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif echo "$PR_TITLE" | grep -iq '\[bump:patch\]'; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Update version in filter list
        run: |
          python scripts/bump_version.py ${{ steps.bump_type.outputs.type }}

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add turk-adfilter.txt
          git commit -m "chore(release): bump ${{ steps.bump_type.outputs.type }} version [skip ci]" || echo "No changes to commit"
          git push

      - name: Create tag
        run: |
          # Get new version from turk-adfilter.txt
          VERSION=$(grep '^! Version:' turk-adfilter.txt | head -n1 | awk '{print $3}')
          git tag $VERSION
          git push origin $VERSION